version: '3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: always
    volumes:
      - /my-db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: employee
      MYSQL_ROOT_PASSWORD: root

  springboot-app:
    container_name: springboot-app
    image: springboot-app
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      #SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/employee?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      #SPRING_DATASOURCE_USERNAME: root
      #SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb